#!/bin/bash

sudo apt update && sudo apt install python3 python3-pip git -y

pip install Flask==2.0.3 pyTelegramBotAPI==4.4.0 mercadopago==1.0.0 psycopg2-binary==2.9.1 requests==2.26.0 waitress==2.1.2 pyngrok==5.1.0 qrcode==7.3 pytz==2021.3 --break-system-packages

git clone https://github.com/Carlosrz2910/BotCCLD

cd BotCCLD
